services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:user
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:user
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  static_site:
    build: ./requirements/bonus/static_site
    image: static_site:user
    container_name: static_site
    restart: always
    volumes:
      - ./requirements/bonus/static_site/src:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    image: nginx:user
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:user
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/neleon/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/neleon/data/wordpress
      o: bind

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    name: inception