services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:user
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - /home/neleon/data/mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:user
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - /home/neleon/data/wordpress:/var/www/wordpress
    networks:
      - inception

  static_site:
    build:
      context: ./requirements/bonus/static_site
    image: static_site:user
    container_name: static_site
    restart: always
    volumes:
      - ./requirements/bonus/static_site/src:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    image: nginx:user
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/sites-enabled/default
      - ./requirements/nginx/tools/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - /home/neleon/data/wordpress:/var/www/wordpress
    networks:
      - inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge
