FROM debian:bookworm-slim

# Installer PHP, les extensions nécessaires, et outils utiles
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        php php-fpm php-mysql curl wget unzip tar mariadb-client less \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Installer wp-cli (outil ligne de commande WordPress)
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# Copier le script d'initialisation
COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Point d'entrée
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
